ALTER TABLE noticias ALTER COLUMN status_id SET DEFAULT 1;

ALTER TABLE monitorias ADD COLUMN status_id integer DEFAULT(1) NOT NULL,
ADD FOREIGN KEY (status_id) REFERENCES status
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE estagios ADD COLUMN status_id integer DEFAULT(1) NOT NULL,
ADD FOREIGN KEY (status_id) REFERENCES status
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE eventos ADD COLUMN status_id integer DEFAULT(1) NOT NULL,
ADD FOREIGN KEY (status_id) REFERENCES status
ON UPDATE CASCADE ON DELETE CASCADE;
